### ISSUE TITLE
Having issue positioning font icon....

### ISSUE THREAD

**Issue by emmatex** [oyes/ofl#5]
Having issue positioning font icon, in bootstrap well..

**Comment by oyekunmi** [comment]
@emmatex Please let your description be more elaborate... which page ? which section of the page ? which icon ?

**Comment by emmatex** [comment]
categories page

**Comment by oyekunmi** [comment]
@emmatex  Which position should the icons be ? Please attach the image of how you want the section or page to look like.

**Comment by emmatex** [comment]
thank for u quick response but i've resolved the issue.
