### ISSUE TITLE
Search Page - Searchbox on Categories.html

### ISSUE THREAD

**Issue by oyekunmi** [oyes/ofl#7]
The search bar on the page needs to be fixed to look like the one in the provided image found in exclude/Search Two,jpg

**Comment by abdullateef97** [comment]
there is no categories.html

**Comment by oyekunmi** [comment]
Please checkout to the Categories branch. That is where the search page development is happening

**Comment by oyekunmi** [comment]
Apply the search box on the Index Page banner to this page
